name: CD using Docker Image

on:
    push:
        branches:
          - 'master'
        paths:
          - .github/workflows/CD.yml
          - twitter/**

env:
    IMAGE: ${{ secrets.NCR_REGISTRY }}/twitter
    IMAGE_TAG: ${{ secrets.NCR_REGISTRY }}/twitter:latest

jobs:
    # Build Image / Push Image to NCR
    build-and-push:
        name: Build and Push Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            # Docker 설치
            - name: Install Docker
              run: |
                sudo apt-get update
                sudo apt-get install -y docker.io

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ secrets.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Copy .env file from secrets
              run: echo "$MY_ENV_CONTENTS" > .env
              env:
                MY_ENV_CONTENTS: ${{ secrets.MY_ENV_SECRETS }}

            - name: Get Current Timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: twitter
                tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
                push: true

    # Pull Image From NCR / Run new container with new image
    deploy-staging:
        needs: build-and-push
        name: deploy to staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: pull and run image
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST_STAGING }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    sudo apt-get update
                    sudo apt-get install -y docker.io

                    docker login \
                    ${{ secrets.NCR_REGISTRY }} \
                     -u ${{ secrets.NCR_ACCESS_KEY_ID }} -p ${{ secrets.NCR_SECRET_KEY }}
                    docker pull ${{ env.IMAGE_TAG }}
                    docker stop twitter && docker rm twitter
                    docker run -p 8000:8000 -d --name twitter \
                    -v ~/.aws:/root/.aws:ro \
                    --env-file .env \
                    likelion-cr-jh.kr.ncr.ntruss.com/twitter:latest